package dev.selenium.ide;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class Test001Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void test001() {
        // Test name: Test001
        // Step # | name | target | value
        // 1 | open | /Login.aspx |
        driver.navigate().to("https://techedge.techcanvass.co/Login.aspx");
        // 2 | type | id=txtLoginid | test
        driver.findElement(By.id("txtLoginid")).sendKeys("test");
        // 3 | type | id=txtpassword | test
        driver.findElement(By.id("txtpassword")).sendKeys("test");
        driver.navigate().refresh();
        driver.navigate().back();

//        System.out.println(driver.getPageSource());
        // 4 | click | id=btnLogin |
        driver.findElement(By.id("btnLogin")).click();





    }
}
